const phoenician = new SlideSet([
  {'A' : ''},
  {'B' : ''},
  {'C' : ''},
  {'D' : ''},
  {'E' : ''},
  {'F' : ''},
  {'G' : ''},
  {'H' : ''},
  {'I' : ''},
  {'J' : ''},
  {'K' : ''},
  {'L' : ''},
  {'M' : ''},
  {'N' : ''},
  {'O' : ''},
  {'P' : ''},
  {'Q' : ''},
  {'R' : ''},
  {'S' : ''},
  {'T' : ''},
  {'U' : ''},
  {'V' : ''},
  {'W' : ''},
  {'X' : ''},
  {'Y' : ''},
  {'Z' : ''},
]);

//``TODO append rtl attributes?
const classicalHebrew = new SlideSet([
  {'א' : 'aleph'},
  {'ב' : 'beth'},
  {'ג' : 'gimel'},
  {'ד' : 'daleth'},
  {'ה' : 'he'},
  {'ו' : 'waw'},
  {'ז' : 'zayin'},
  {'ח' : 'heth'},
  {'ט' : 'teth'},
  {'י' : 'yodh'},
  {'כ' : 'kaph'},
  {'ל' : 'lamedh'},
  {'מ' : 'mem'},
  {'נ' : 'nun'},
  {'ס' : 'samekh'},
  {'ע' : 'ayin'},
  {'פ' : 'pe'},
  {'צ' : 'sadhe'},
  {'ק' : 'qoph'},
  {'ר' : 'resh'},
  {'ש' : 'shin'},
  {'ת' : 'taw'},
]);

const greek = new SlideSet([
  {'Α α' : 'alpha'},
  {'Β β' : 'beta'},
  {'Γ γ' : 'gamma'},
  {'Δ δ' : 'delta'},
  {'Ε ε' : 'epsilon'},
  {'Ζ ζ' : 'zeta'},
  {'Η η' : 'eta'},
  {'Θ θ' : 'theta'},
  {'Ι ι' : 'iota'},
  {'Κ κ' : 'kappa'},
  {'Λ λ' : 'lambda'},
  {'Μ μ' : 'mu'},
  {'Ν ν' : 'nu'},
  {'Ξ ξ' : 'xi'},
  {'Ο ο' : 'omicron'},
  {'Π π' : 'pi'},
  {'Ρ ρ' : 'rho'},
  {'Σ σ' : 'sigma'},
  {'Τ τ' : 'tau'},
  {'Υ υ' : 'upsilon'},
  {'Φ φ' : 'phi'},
  {'Χ χ' : 'chi'},
  {'Ψ ψ' : 'psi'},
  {'Ω ω' : 'omega'},
]);


